from turtle import Screen, Turtle


pantalla = Screen()
pantalla.setup(425, 225)
pantalla.screensize(400, 200)

# Diseña un programa que dibuje un cuadrado cuyo lado mida 200 pasos y otro cuadrado de lado 100 centrado en su interior.
# El cuadrado exterior ha de ser de color rojo y el interior de color azul.
tortuga = Turtle()
tortuga.pensize(10)
tortuga.color('red')
tortuga.penup()
tortuga.goto(-100, -100)
tortuga.pendown()
tortuga.forward(200)
tortuga.left(90)
tortuga.forward(200)
tortuga.left(90)
tortuga.forward(200)
tortuga.left(90)
tortuga.forward(200)
tortuga.left(90)
tortuga.penup()
tortuga.color('blue')
tortuga.goto(-50, -50)
tortuga.pendown()
tortuga.forward(100)
tortuga.left(90)
tortuga.forward(100)
tortuga.left(90)
tortuga.forward(100)
tortuga.left(90)
tortuga.forward(100)

#No uses los métodos left o right.
tortuga.pensize(3)
tortuga.color('blue')
tortuga.penup()
tortuga.goto(-100, -100)
tortuga.pendown()
tortuga.setheading(0)
tortuga.forward(200)
tortuga.setheading(90)
tortuga.forward(200)
tortuga.setheading(180)
tortuga.forward(200)
tortuga.setheading(270)
tortuga.forward(200)
tortuga.penup()
tortuga.color('red')
tortuga.goto(-50, -50)
tortuga.pendown()
tortuga.setheading(0)
tortuga.forward(100)
tortuga.setheading(90)
tortuga.forward(100)
tortuga.setheading(180)
tortuga.forward(100)
tortuga.setheading(270)
tortuga.forward(100)

pantalla.exitonclick()